// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoBOHVFp0eqzSxtD3cm7s3ZVP1AfMqg4g',
    appId: '1:387879577336:web:ea789866c5e87efb24bd0d',
    messagingSenderId: '387879577336',
    projectId: 'teenworkly',
    authDomain: 'teenworkly.firebaseapp.com',
    storageBucket: 'teenworkly.firebasestorage.app',
    measurementId: 'G-356RERC6QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_2FUwRo3tu-Yh4cuYW49Acngbm7XDYHE',
    appId: '1:387879577336:android:6469fa24c8f34ec824bd0d',
    messagingSenderId: '387879577336',
    projectId: 'teenworkly',
    storageBucket: 'teenworkly.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYSxGEwdroVHf8kJOEfImkRQAKjkzybAg',
    appId: '1:387879577336:ios:f9f6b1bb0d6d3f5324bd0d',
    messagingSenderId: '387879577336',
    projectId: 'teenworkly',
    storageBucket: 'teenworkly.firebasestorage.app',
    iosBundleId: 'com.example.teenWorkly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYSxGEwdroVHf8kJOEfImkRQAKjkzybAg',
    appId: '1:387879577336:ios:f9f6b1bb0d6d3f5324bd0d',
    messagingSenderId: '387879577336',
    projectId: 'teenworkly',
    storageBucket: 'teenworkly.firebasestorage.app',
    iosBundleId: 'com.example.teenWorkly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoBOHVFp0eqzSxtD3cm7s3ZVP1AfMqg4g',
    appId: '1:387879577336:web:b9ade2d0cba3b60024bd0d',
    messagingSenderId: '387879577336',
    projectId: 'teenworkly',
    authDomain: 'teenworkly.firebaseapp.com',
    storageBucket: 'teenworkly.firebasestorage.app',
    measurementId: 'G-P70ZLGH1EP',
  );
}
